server:
  port: 7002
  error:
    include-message: always

logging:
  level:
    root: info
    com.luv4code: debug
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
server:
  port: 8080
