server:
  port: 7001
  error:
    include-message: always


logging:
  level:
    root: info
    com.luv4code: debug
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080
